openapi: 3.0.0
info:
  title: Cross-Mind Consensus API
  description: Multi-LLM consensus system for enhanced AI decision making
  version: 2.0.0
  contact:
    name: Cross-Mind Consensus Support
    url: https://github.com/your-repo/cross-mind-consensus

servers:
  - url: https://your-domain.com/api
    description: Production server
  - url: http://localhost:8000
    description: Development server

security:
  - ApiKeyAuth: []

paths:
  /consensus:
    post:
      operationId: getConsensus
      summary: Get multi-LLM consensus on a question
      description: |
        Submit a question to multiple LLM models and receive a consensus response.
        This is the primary endpoint for getting expert opinions from multiple AI models.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: The question to ask multiple LLMs
                  example: "What are the key factors for successful project management?"
                method:
                  type: string
                  enum: ["expert_roles", "direct_consensus", "debate"]
                  default: "expert_roles"
                models:
                  type: array
                  items:
                    type: string
                  description: Specific models to use (optional)
                  example: ["openai_gpt4", "anthropic_claude", "cohere_command"]
                max_models:
                  type: integer
                  minimum: 2
                  maximum: 10
                  default: 5
                  description: Maximum number of models to use
                temperature:
                  type: number
                  minimum: 0.0
                  maximum: 2.0
                  default: 0.7
                  description: Controls randomness in responses
                enable_caching:
                  type: boolean
                  default: true
                  description: Whether to use cached responses
      responses:
        '200':
          description: Successful consensus response
          content:
            application/json:
              schema:
                type: object
                properties:
                  consensus_response:
                    type: string
                    description: The final consensus answer
                  consensus_score:
                    type: number
                    minimum: 0
                    maximum: 1
                    description: How much the models agreed (0-1)
                  individual_responses:
                    type: array
                    items:
                      type: object
                      properties:
                        model:
                          type: string
                        response:
                          type: string
                        confidence:
                          type: number
                        response_time:
                          type: number
                  method_used:
                    type: string
                  total_response_time:
                    type: number
                  models_used:
                    type: array
                    items:
                      type: string
                  cache_hit:
                    type: boolean
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded
        '500':
          description: Internal server error

  /consensus/batch:
    post:
      operationId: getBatchConsensus
      summary: Process multiple questions in batch
      description: Submit multiple questions for batch processing with consensus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - questions
              properties:
                questions:
                  type: array
                  items:
                    type: string
                  maxItems: 50
                  description: List of questions to process
                  example: ["What is machine learning?", "How does blockchain work?"]
                method:
                  type: string
                  enum: ["expert_roles", "direct_consensus", "debate"]
                  default: "expert_roles"
                batch_mode:
                  type: string
                  enum: ["parallel", "sequential"]
                  default: "parallel"
                  description: How to process the batch
      responses:
        '200':
          description: Batch processing results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          type: string
                        consensus_response:
                          type: string
                        consensus_score:
                          type: number
                        success:
                          type: boolean
                        error:
                          type: string
                  batch_summary:
                    type: object
                    properties:
                      total_questions:
                        type: integer
                      successful:
                        type: integer
                      failed:
                        type: integer
                      total_time:
                        type: number

  /models:
    get:
      operationId: getAvailableModels
      summary: Get list of available LLM models
      description: Retrieve information about all available LLM models and their status
      responses:
        '200':
          description: List of available models
          content:
            application/json:
              schema:
                type: object
                properties:
                  models:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        provider:
                          type: string
                        available:
                          type: boolean
                        response_time_avg:
                          type: number
                        success_rate:
                          type: number
                        cost_per_token:
                          type: number

  /analytics/performance:
    get:
      operationId: getPerformanceAnalytics
      summary: Get system performance analytics
      description: Retrieve detailed performance metrics and analytics
      parameters:
        - name: timeframe
          in: query
          schema:
            type: string
            enum: ["1h", "24h", "7d", "30d"]
            default: "24h"
          description: Time period for analytics
        - name: metric_type
          in: query
          schema:
            type: string
            enum: ["consensus_scores", "response_times", "model_performance", "success_rates"]
          description: Specific metric to retrieve
      responses:
        '200':
          description: Performance analytics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  timeframe:
                    type: string
                  metrics:
                    type: object
                    properties:
                      avg_consensus_score:
                        type: number
                      avg_response_time:
                        type: number
                      total_queries:
                        type: integer
                      success_rate:
                        type: number
                      cache_hit_rate:
                        type: number
                  model_performance:
                    type: array
                    items:
                      type: object
                      properties:
                        model_id:
                          type: string
                        avg_response_time:
                          type: number
                        success_rate:
                          type: number
                        consensus_contribution:
                          type: number

  /health:
    get:
      operationId: getHealthStatus
      summary: Check system health
      description: Get the current health status of the system and all components
      responses:
        '200':
          description: System health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["healthy", "degraded", "unhealthy"]
                  timestamp:
                    type: string
                    format: date-time
                  services:
                    type: object
                    properties:
                      api:
                        type: string
                        enum: ["up", "down"]
                      redis:
                        type: string
                        enum: ["up", "down"]
                      models:
                        type: object
                        additionalProperties:
                          type: string
                          enum: ["up", "down", "rate_limited"]
                  system_metrics:
                    type: object
                    properties:
                      cpu_usage:
                        type: number
                      memory_usage:
                        type: number
                      cache_size:
                        type: integer

  /feedback:
    post:
      operationId: submitFeedback
      summary: Submit feedback on consensus response
      description: Provide feedback to improve future consensus responses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - consensus_id
                - rating
              properties:
                consensus_id:
                  type: string
                  description: ID of the consensus response
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: Rating from 1-5
                feedback_text:
                  type: string
                  description: Optional feedback text
                improvement_suggestions:
                  type: array
                  items:
                    type: string
                  description: Specific suggestions for improvement
      responses:
        '200':
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

# GPT-specific configuration
x-gpt-config:
  name: "Cross-Mind Consensus"
  description: "Get expert consensus from multiple AI models on complex questions"
  instructions: |
    You are the Cross-Mind Consensus GPT, designed to help users get well-rounded, 
    expert opinions by consulting multiple AI models simultaneously.

    Key capabilities:
    1. Multi-model consensus on complex questions
    2. Expert role-based analysis 
    3. Batch processing for multiple questions
    4. Performance analytics and insights
    5. System health monitoring

    Usage patterns:
    - Use /consensus for single complex questions requiring expert analysis
    - Use /consensus/batch for processing multiple related questions
    - Check /models to see which AI models are currently available
    - Monitor performance with /analytics/performance
    - Always check /health before critical operations

    Best practices:
    - For controversial topics, explicitly mention you're using multiple AI perspectives
    - When consensus scores are low (<0.7), acknowledge the disagreement between models
    - For technical questions, consider using the "expert_roles" method
    - Use batch processing for research tasks with multiple questions

  conversation_starters:
    - "I need expert analysis on a complex business decision"
    - "Help me understand multiple perspectives on this controversial topic"
    - "I have several related questions that need thorough analysis"
    - "What's the current performance of the consensus system?" 