services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: consensus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      sh -c '
      if [ -n "$REDIS_PASSWORD" ]; then
        redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"
      else
        redis-server --appendonly yes
      fi'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Cross-Mind Consensus API
  api:
    build:
      context: ../../
      dockerfile: config/docker/Dockerfile
      target: production
    container_name: consensus-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENABLE_CACHING=true
      - ENABLE_ANALYTICS=true
      - ENABLE_RATE_LIMITING=true
    volumes:
      - ../../logs:/app/logs
      - ../../.env:/app/.env:ro
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Dashboard
  dashboard:
    build:
      context: ../../
      dockerfile: config/docker/Dockerfile
      target: development
    container_name: consensus-dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    volumes:
      - ../../.env:/app/.env:ro
    depends_on:
      api:
        condition: service_healthy
    command: ["streamlit", "run", "src/streamlit_dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

  # Nginx Load Balancer & Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: consensus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/ssl:/etc/nginx/ssl:ro
      - /var/www/letsencrypt:/var/www/letsencrypt:ro
    depends_on:
      - api
      - dashboard

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: consensus-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    user: "65534:65534"  # nobody:nobody
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: consensus-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "472:472"  # grafana:grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
    volumes:
      - ../../data/grafana:/var/lib/grafana
      - ../monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: consensus-network
    driver: bridge 