# AI Models Configuration
# This file defines all available AI models and their configurations

models:
  # OpenAI Models
  openai_gpt4:
    provider: "openai"
    model_name: "gpt-4"
    display_name: "GPT-4"
    api_key_env: "OPENAI_API_KEY"
    endpoint: "https://api.openai.com/v1/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.03
    
  openai_gpt4_turbo:
    provider: "openai"
    model_name: "gpt-4-turbo"
    display_name: "GPT-4 Turbo"
    api_key_env: "OPENAI_API_KEY"
    endpoint: "https://api.openai.com/v1/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.01

  openai_gpt35_turbo:
    provider: "openai"
    model_name: "gpt-3.5-turbo"
    display_name: "GPT-3.5 Turbo"
    api_key_env: "OPENAI_API_KEY"
    endpoint: "https://api.openai.com/v1/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.002

  # Anthropic Models
  anthropic_claude3_opus:
    provider: "anthropic"
    model_name: "claude-3-opus-20240229"
    display_name: "Claude 3 Opus"
    api_key_env: "ANTHROPIC_API_KEY"
    endpoint: "https://api.anthropic.com/v1/messages"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.015

  anthropic_claude3_sonnet:
    provider: "anthropic"
    model_name: "claude-3-sonnet-20240229"
    display_name: "Claude 3 Sonnet"
    api_key_env: "ANTHROPIC_API_KEY"
    endpoint: "https://api.anthropic.com/v1/messages"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.003

  anthropic_claude3_haiku:
    provider: "anthropic"
    model_name: "claude-3-haiku-20240307"
    display_name: "Claude 3 Haiku"
    api_key_env: "ANTHROPIC_API_KEY"
    endpoint: "https://api.anthropic.com/v1/messages"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.00025

  # Google Models
  google_gemini_pro:
    provider: "google"
    model_name: "gemini-pro"
    display_name: "Gemini Pro"
    api_key_env: "GOOGLE_API_KEY"
    endpoint: "https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.0005

  google_gemini_pro_vision:
    provider: "google"
    model_name: "gemini-pro-vision"
    display_name: "Gemini Pro Vision"
    api_key_env: "GOOGLE_API_KEY"
    endpoint: "https://generativelanguage.googleapis.com/v1/models/gemini-pro-vision:generateContent"
    max_tokens: 4096
    temperature: 0.7
    enabled: false
    cost_per_1k_tokens: 0.0005

  # ZHIPUAI Models (智谱AI)
  zhipuai_glm4_air:
    provider: "zhipuai"
    model_name: "glm-4-air"
    display_name: "GLM-4-Air (思维链专家)"
    api_key_env: "ZHIPUAI_API_KEY"
    endpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.001
    specialties: ["Chinese language", "chain-of-thought reasoning", "philosophical analysis"]
    chain_of_thought_optimized: true

  zhipuai_glm4:
    provider: "zhipuai"
    model_name: "glm-4"
    display_name: "GLM-4"
    api_key_env: "ZHIPUAI_API_KEY"
    endpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.01

  zhipuai_glm3_turbo:
    provider: "zhipuai"
    model_name: "glm-3-turbo"
    display_name: "GLM-3 Turbo"
    api_key_env: "ZHIPUAI_API_KEY"
    endpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: true
    cost_per_1k_tokens: 0.005

  # Cohere Models
  cohere_command:
    provider: "cohere"
    model_name: "command"
    display_name: "Command"
    api_key_env: "COHERE_API_KEY"
    endpoint: "https://api.cohere.ai/v1/generate"
    max_tokens: 4096
    temperature: 0.7
    enabled: false
    cost_per_1k_tokens: 0.015

  # Mistral Models
  mistral_large:
    provider: "mistral"
    model_name: "mistral-large-latest"
    display_name: "Mistral Large"
    api_key_env: "MISTRAL_API_KEY"
    endpoint: "https://api.mistral.ai/v1/chat/completions"
    max_tokens: 4096
    temperature: 0.7
    enabled: false
    cost_per_1k_tokens: 0.008

# Default model selection for consensus
default_models:
  - "openai_gpt4"
  - "anthropic_claude3_sonnet"
  - "zhipuai_glm4_air"
  - "google_gemini_pro"

# Provider configurations
providers:
  openai:
    name: "OpenAI"
    auth_type: "bearer"
    rate_limit: 60  # requests per minute
    timeout: 30
    
  anthropic:
    name: "Anthropic"
    auth_type: "x-api-key"
    rate_limit: 60
    timeout: 30
    
  google:
    name: "Google"
    auth_type: "api_key"
    rate_limit: 60
    timeout: 30
    
  zhipuai:
    name: "智谱AI (ZHIPUAI)"
    auth_type: "bearer"
    rate_limit: 60
    timeout: 30
    
  cohere:
    name: "Cohere"
    auth_type: "bearer"
    rate_limit: 60
    timeout: 30
    
  mistral:
    name: "Mistral AI"
    auth_type: "bearer"
    rate_limit: 60
    timeout: 30 